//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietToaThuoc
    {
        public int STT { get; set; }
        public int Thuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string LieuDung { get; set; }
    
        public virtual tThuoc tThuoc { get; set; }
        public virtual tToaThuoc tToaThuoc { get; set; }
    }
}
