//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tThuoc()
        {
            this.tChiTietToaThuocs = new HashSet<tChiTietToaThuoc>();
        }
    
        public string TenThuoc { get; set; }
        public string NuocSX { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string HanSuDung { get; set; }
        public string GhiChu { get; set; }
        public int MaThuoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietToaThuoc> tChiTietToaThuocs { get; set; }
    }
}
