//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tToaThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tToaThuoc()
        {
            this.tChiTietToaThuocs = new HashSet<tChiTietToaThuoc>();
        }
    
        public int STT { get; set; }
        public string BenhNhan { get; set; }
        public string BenhDuocChanDoan { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
    
        public virtual tBenhNhan tBenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietToaThuoc> tChiTietToaThuocs { get; set; }
    }
}
